attributes:
  # default 是初始值；min/max 是有效範圍。
  attack:
    display-name: "&c攻擊力"
    default: 0
    min: 0
    max: 1000000
  defense:
    display-name: "&9防禦力"
    default: 0
    min: 0
    max: 1000000
  health:
    display-name: "&a生命值"
    default: 20
    min: 0
    max: 1000000
