general:
  # 全局訊息前綴；& 代表顏色碼。
  prefix: "&d[LDAPI] &r"
  # 正式環境建議關閉。
  debug: false
  command-prefix: ld
  lore:
    enabled: true
    ignore-color: true
    id-keys: [indierpg-id, item-id, mythic-id, namespace, jewelry-id, card-id, soul-bead-id]
