mythicmobs:
  # false 會停用事件綁定，但不影響 LDAPI 其他功能。
  enabled: true
  api-version: "4.13.0"
  events:
    ldapi_boss:
      # 必須對應 MythicMobs 怪物 internal name。
      spawn:
        skill: LDAPI_BOSS_SPAWN
      death:
        chance: 1.0
        skill: LDAPI_BOSS_DEATH
        gold: 500
        battlepass-xp: 50
        item: growth_core
        command: ""
    mythic_zombie:
      death:
        chance: 0.25
        gold: 25
        battlepass-xp: 10
        item: growth_core
