shop:
  enabled: true
  menu-title: "&6&lLDAPI 商店 &7[金幣：{gold}]"
  items:
    growth_core:
      price: 80
      material: EMERALD
      display-name: "&b成長核心"
      item: growth_core
      slot: 11
    abyss_ring:
      price: 300
      material: DIAMOND
      display-name: "&5深淵戒指"
      item: abyss_ring
      slot: 15
